In [1]:
import torch
import numpy as np

## Tensor Basics

In [2]:
torch.__version__

'1.1.0'

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
arr.dtype

[1 2 3 4 5]


dtype('int32')

In [4]:
type(arr)

numpy.ndarray

In [5]:
# Convert numpy array to pytorch tensor
x = torch.from_numpy(arr)

In [6]:
type(x)

torch.Tensor

In [7]:
# This one works with more than just numpy arrays
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [8]:
x.dtype

torch.int32

In [9]:
arr2d = np.arange(0.0,12.0)

In [10]:
arr2d = arr2d.reshape(4,3)

In [11]:
x2 = torch.as_tensor(arr2d)

In [12]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [13]:
# Link exist between numpy array and the tensor object
arr[0] = 99
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [14]:
# Often this is not desirable so use torch.tensor.  The linkage is demonstrated in the code below
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [16]:
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [17]:
my_arr[0] = 9999

In [18]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [19]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       dtype=torch.int32)

In [20]:
## Create tensors from scratch using pytorch

In [21]:
new_arr = np.array([1,2,3])
new_arr.dtype

dtype('int32')

In [22]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
my_tensor = torch.Tensor(new_arr)   # Converts to floats, does not pass in datatype.
my_tensor

tensor([1., 2., 3.])

In [26]:
torch.empty(4,2)  # Create numbers very close to 0

tensor([[0.0000e+00, 9.6429e-39],
        [1.8754e+28, 8.0439e+20],
        [3.3425e+21, 1.2916e-11],
        [2.7598e-06, 1.7186e-04]])

In [28]:
torch.zeros(4,3, dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [30]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [32]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [33]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [36]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [37]:
# Change dtype
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [38]:
torch.rand(4,3) # Random Sample of uniform distribution ~ [0,1]

tensor([[0.6786, 0.0652, 0.9203],
        [0.4325, 0.9638, 0.8130],
        [0.8966, 0.2244, 0.7970],
        [0.3941, 0.2934, 0.4947]])

In [40]:
torch.randn(4,3) # Random sample of standard random distribution with mean = 0 sd = 1

tensor([[ 1.7966, -0.1215, -0.9039],
        [ 1.7037,  0.9285,  0.8340],
        [ 1.1887, -0.6401,  1.2225],
        [ 0.1006,  0.2584,  0.8006]])

In [46]:
torch.randint(low=0, high=10, size= (5,5)) # Randomoly choose between low and high.  High is exclusive like normal

tensor([[0, 6, 6, 1, 4],
        [8, 2, 9, 9, 8],
        [4, 3, 5, 0, 3],
        [1, 2, 2, 0, 3],
        [7, 2, 3, 1, 3]])

In [48]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [49]:
x.shape

torch.Size([2, 5])

In [50]:
torch.rand_like(x) # Assumes shape

tensor([[0.8088, 0.7771, 0.7611, 0.1966, 0.8211],
        [0.2668, 0.2749, 0.1424, 0.9261, 0.9702]])

In [51]:
torch.randn_like(x) # Assumes shape

tensor([[-1.3953, -0.4259,  1.1091,  0.5802, -1.1964],
        [-0.4129,  1.6759,  2.6803, -0.2144,  0.0607]])

In [52]:
torch.randint_like(x,low=0, high=11) # Assumes shape

tensor([[ 6.,  5.,  1.,  3., 10.],
        [ 5.,  9.,  6.,  0.,  1.]])

In [54]:
torch.manual_seed(42)

## Tensor Operations

In [60]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [65]:
x[1,1] # Returns back tensor object

tensor(3)

In [69]:
x[:,1] # indxesing for the column

tensor([1, 3, 5])

In [71]:
x[:,1:] # Slicing for the column, keeps shape

tensor([[1],
        [3],
        [5]])

In [73]:
# View and Reshape
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [76]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [80]:
x = x.reshape(2,5)

In [81]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [85]:
# Views reflect the most current data
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
x.shape

torch.Size([10])

In [88]:
z = x.view(2,5)

In [89]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [92]:
# z is linked to x
x[0] = 9999
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [93]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
x.shape

torch.Size([10])

In [97]:
# -1 Infer as to what the second dimension should be
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [100]:
x = torch.arange(11)
## x.view(2,-1) # Gives an error 11 not divisible by 2, can't infer

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
a = torch.tensor([1.,2.,3.])
a

tensor([1., 2., 3.])

In [107]:
b = torch.tensor([4.,5.,6.])
b

tensor([4., 5., 6.])

In [108]:
a + b

tensor([5., 7., 9.])

In [109]:
torch.add(a,b)

tensor([5., 7., 9.])

In [110]:
a.mul(b)

tensor([ 4., 10., 18.])

In [112]:
a.mul_(b) # Equivalent to a = a * b
a

tensor([ 4., 10., 18.])

In [116]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [119]:
# Dot Product multiplication
a.dot(b)

tensor(32.)

In [123]:
a = torch.tensor([[0,2,4],[1,3,5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [125]:
b = torch.tensor([[6,7],[8,9],[10,11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [126]:
torch.mm(a,b) ## mm is matric multiplcation

tensor([[56, 62],
        [80, 89]])

In [128]:
a@b # Another way of doing it.  Use torch.mm for readability

tensor([[56, 62],
        [80, 89]])

In [130]:
x = torch.tensor([2.,3.,4.,5.])
x

tensor([2., 3., 4., 5.])

In [131]:
x.norm() # Euclidian Distance

tensor(7.3485)

In [133]:
x.numel() # Number of elements

4

In [134]:
len(x) # Avoid usign this method - use numel()

4

In [135]:
len(a)

2

In [136]:
a.numel()

6